-- Create the garages table
create table if not exists garages (
  id bigint generated by default as identity primary key,
  registration_number text unique not null,
  name text,
  name_en text,
  branch_name text,
  branch_name_en text,
  address text,
  address_en text,
  district text,
  district_en text,
  phone text,
  services text,
  services_en text,
  vehicle_types text, -- Storing as comma separated string for simplicity, or use text[] if preferred
  service_tags text[], -- Array of text for smart tags
  opening_hours text,
  rating float4 default 0,
  review_count int4 default 0,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table garages enable row level security;

-- Create a policy that allows everyone to read data
drop policy if exists "Enable read access for all users" on garages;
create policy "Enable read access for all users"
on garages for select
using (true);

-- Create a policy that allows service_role (us during migration) to insert data
drop policy if exists "Enable insert for service_role only" on garages;
create policy "Enable insert for service_role only"
on garages for insert
with check (true);
-- Note: By default, service_role bypasses RLS, but explicit policies help when testing with other roles. 
-- For simplicity in this demo, we allow public read. 

-- Create the service_requests table
create table if not exists service_requests (
  id text primary key,
  category_id text not null,
  car_model text not null,
  year text,
  description text,
  location text,
  urgency text,
  status text default 'pending',
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  user_phone text
);

-- Enable Row Level Security (RLS)
alter table service_requests enable row level security;

-- Create a policy that allows everyone to read data
drop policy if exists "Enable read access for all users" on service_requests;
create policy "Enable read access for all users"
on service_requests for select
using (true);

-- Create a policy that allows everyone to insert data for this demo
drop policy if exists "Enable insert for all users" on service_requests;
create policy "Enable insert for all users"
on service_requests for insert
with check (true);
